// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Priyarank.Data;

namespace Priyarank.Migrations
{
    [DbContext(typeof(RankContext))]
    partial class RankContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Priyarank.Models.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new Guid("343df5ee-8e26-4de5-90b7-86cb56a60d6a"));

                    b.Property<Guid?>("Team1Id");

                    b.Property<Guid?>("Team2Id");

                    b.Property<bool>("_played");

                    b.Property<DateTime>("_playedOn");

                    b.Property<DateTime>("created")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTime(2019, 3, 27, 8, 15, 57, 159, DateTimeKind.Local).AddTicks(5158));

                    b.Property<Guid?>("loserId");

                    b.Property<Guid?>("winnerId");

                    b.HasKey("Id");

                    b.HasIndex("Team1Id");

                    b.HasIndex("Team2Id");

                    b.HasIndex("loserId");

                    b.HasIndex("winnerId");

                    b.ToTable("Match");
                });

            modelBuilder.Entity("Priyarank.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("Priyarank.Models.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new Guid("3b324b07-cea8-479f-adfe-67d6c6af3006"));

                    b.Property<int>("Draws");

                    b.Property<int>("Elo")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(1200);

                    b.Property<int>("Losses");

                    b.Property<string>("Name");

                    b.Property<int>("Wins");

                    b.HasKey("Id");

                    b.ToTable("Team");
                });

            modelBuilder.Entity("Priyarank.Models.Match", b =>
                {
                    b.HasOne("Priyarank.Models.Team", "Team1")
                        .WithMany()
                        .HasForeignKey("Team1Id");

                    b.HasOne("Priyarank.Models.Team", "Team2")
                        .WithMany()
                        .HasForeignKey("Team2Id");

                    b.HasOne("Priyarank.Models.Team", "loser")
                        .WithMany()
                        .HasForeignKey("loserId");

                    b.HasOne("Priyarank.Models.Team", "winner")
                        .WithMany()
                        .HasForeignKey("winnerId");
                });
#pragma warning restore 612, 618
        }
    }
}
